### PR TITLE
Remove `WithPrimis` from CSS selectors

### PR DESCRIPTION
**Pull request by cvzi**

### CODE REVIEW

**Comment by cvzi** [comment]
@cyfung1031 Can you test this please

I don't see any class names containing `WithPrimis` when I open a song on genius.com. So I think I am getting a different Genius page than you get. Maybe they have different style for different countries?

**Comment by cyfung1031** [comment]
> 

Oh Really? The difference is just "WithPrimis" right??

Screen Shot 2022-12-21 at 11 09 29

**Comment by cyfung1031** [comment]
I just checked that only Microsoft Edge would have the `WithPrimis`.
Opera 93, Safari 15.6.1, Firefox 88, Firefox 107 do not have. (I have not installed Chrome on my Mac...)

Same result for both private mode and normal mode. not due to cookies or localStorage.
Let me do some review for this pull request first.

By the way, could you please check from your side that whether Microsoft Edge would give this `WithPrimis` class? 
Thank you.

**Comment by cyfung1031** [comment]
As per searching, only inline styling in genius.com contains these `WithPrimis` for unknown reasons.

Screen Shot 2022-12-21 at 13 08 40

**Comment by cyfung1031** [comment]
I have found that it is cookie related. I don't know why my cookie was set to Primis.
You can try it yourself.

Install my little userscript for easy testing
https://github.com/cyfung1031/userscript-supports/raw/main/cookie-manager.user.js

cook._genius_ab_test_cohort = 0 can enable
cook._genius_ab_test_cohort = null can disable

change cookie and refresh the page

**Comment by cyfung1031** [comment]
for the existing four themes, can you use pure css rules to replace them completely?
I noticed that there are many onload functions.
I think some onload functions are still needed like base url 
however these all onload functions shall be common for all themes. not theme specific.
I want to reduce the duplications for three schemes with `combine()` and `scripts()`

actually if you set the color stuffs as custom CSS properties, it is more easy for customization.

for example,
```
 html[theme-selected="white"]{
     --egl-color:white;
     --egl-background:black;
}
 html[theme-selected="black"]{
     --egl-color:black;
     --egl-background:white;
}
 span{
     color: var(--egl-color, '#fff');
}
 span > a{
     color: inherit;
}
```

**Comment by cyfung1031** [comment]
for the no use stuff, just `display: none !important;`
no rendering or layout calculation for `display: none`

**Comment by cyfung1031** [comment]
@cvzi I have redefined the styles. Now it can works for both `desktop_react` and `desktop_react_atf`
https://github.com/cvzi/genius-lyrics-userscript/tree/test-content-styling

You can try it with Spotify Genius Lyrics
https://github.com/cyfung1031/Spotify-Genius-Lyrics-userscript/tree/test-content-styling

**Review by cyfung1031 — COMMENTED** [review]
To be replaced by 
https://github.com/cvzi/genius-lyrics-userscript/tree/test-content-styling

**Comment by cvzi** [comment]
Looks good on Spotify for both desktop_react and desktop_react_atf

**Comment by cvzi** [comment]
Unrelated question: Can you read/write Simplified Chinese? I need someone to review some Simplified Chinese in [another project](https://github.com/carpedm20/emoji/issues/212#issuecomment-1362910944).

**Comment by cyfung1031** [comment]
> Looks good on Spotify for both desktop_react and desktop_react_atf

You will check the PR and merge it? Or already ok to merge?

**Comment by cvzi** [comment]
Thanks for reminder, I forgot to merge, I already looked at it

**Pull request closed without merging**
